### ISSUE TITLE
notificationclick don't check for opened tabs

### ISSUE THREAD

**Issue by jpenna** [GoogleChrome/push-notifications#18]
The `notificationclick` method is said to check for opened tabs and only open a new tab if the URL isn't already open. It isn't working like this. Even if I have the tab opened, clicking the push open a new tab on the same URL again.

From the tutorial:
> "This code checks all window clients for this Service Worker; if the requested URL is already open in a tab, focus on it — otherwise open a new tab for it."

**Comment by gauntface** [comment]
This is a bug in the codelab.

The list of window clients will only return windows that are for the same domain as the website subscribing for push, this prevents snooping on what users are viewing.

This will be fixed in: #17 

I've also jotted down some more info here: https://web-push-book.gauntface.com/chapter-05/04-common-notification-patterns/#focus-an-existing-window

**Comment by jpenna** [comment]
Cool! Thanks for the explanation
