### ISSUE TITLE
Not getting Push message from Push Companion Site

### ISSUE THREAD

**Issue by hitgubsenthil** [GoogleChrome/push-notifications#32]
I have followed codelab steps and created successfully push notification sample and able to get notification from Devtool when I click push. But when I copy paste the subscription and pushed message from Push Companion Site, I didn't get push notification on my browser.

**Comment by ajdf24** [comment]
+1

**Comment by gauntface** [comment]
Few things:

1. Are you certain the application server key from the companion site is the same as the one in your web app? If it is, could you try refreshing the keys, adding them to your codelab code and then unsubscribing and re-subscribing
1. I recently altered the codelab and the companion site so that it wouldn't actually allow the subscription details if it's copied from the console (The console truncates the subscription and this catches out so many people - myself included). Could you have been hitting this?

**Comment by lucasumberto** [comment]
Hello!
I ended the codelab and could not make Push Companion work on Chrome 54.0.2840.59 (64-bit), but worked fine on Firefox 54.0 (64-bit) ...

Is there anything that might be causing Pus incompatibility with chrome? Or can it be some chrome configuration on my machine?

**Comment by gauntface** [comment]
chrome on your machine could have hit an old bug where the GCM database becomes corrupt. (I think Chrome 54 is quite old now).

**Comment by lucasumberto** [comment]
@gauntface Thanks man, my chrome was not with auto update enabled... shame on me

**Comment by gauntface** [comment]
@lucasumberto no worries, going to close this for now but please re-open if you are still hitting problems.
